server:
  port: 8081


spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: KuzPsina
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    default-schema: auth-schema

application:
  security:
    jwt:
      secret-key: 4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c
      expiration: 86400000
      refresh-token:
        expiration: 604800000
