server:
  port: 8083

spring:
  application:
    name: patient-service
  datasource:
    url: jdbc:postgresql://localhost:5432/patient
    username: postgres
    password: KuzPsina
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    default-schema: patient-schema

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

application:
  security:
    jwt:
      secret-key: 4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c
      expiration: 86400000

logging:
  level:
    org:
      springframework:
        security: trace
